### ISSUE TITLE
can this software be used on windows 

### ISSUE THREAD

**Issue by Green10026** [paulo-raca/adb-proxy#6]

**Comment by paulo-raca** [comment]
I believe so.

I haven't tested it, but I don't anticipate any reason why it wouldn't work. 

Please give it a try and let me know. I will look into it you run into any issues

**Comment by Green10026** [comment]
I have tried to compile it but i run into issues on windows as sys/socket.h is for linux only, can you please work a fix around this ?

**Comment by paulo-raca** [comment]
Can you send me build log?

**Comment by paulo-raca** [comment]
I managed to install it on Windows without any issues.

The only tricky part is setting up Visual Studio Build Tools, necessary for [netifaces](https://pypi.org/project/netifaces/), required for upnp support:

> building 'netifaces' extension
> error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/

I managed to compile it successfully by downloading `vs_buildtools.exe` from that link and running it with this command:

```vs_buildtools.exe --norestart --passive --downloadThenInstall --includeRecommended --add Microsoft.VisualStudio.Workload.NativeDesktop --add Microsoft.VisualStudio.Workload.VCTools --add Microsoft.VisualStudio.Workload.MSBuildTools```

Credits to [Ice Bear](https://stackoverflow.com/users/14425271/ice-bear) on [StackOverflow](https://stackoverflow.com/a/64262038/995480)

**Comment by paulo-raca** [comment]
However I'll update the library so that UPNP and AWS support are optional -- These gave me headaches before

**Comment by Green10026** [comment]
thanks a lot for your support, it is very much appreciated
